export const eyeColors = [
  {
    label: 'Selecione um ton de seus olhos',
    value: '',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Azul-clara',
    value: 'Azul-clara',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Azul-esverdeada',
    value: 'Azul-esverdeada',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Cinza',
    value: 'Cinza',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Azul-escura',
    value: 'Azul-escura',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Azul-cinza',
    value: 'Azul-cinza',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Cinza-verde',
    value: 'Cinza-verde',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Verde',
    value: 'Verde',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Avelã',
    value: 'Avelã',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Âmbar',
    value: 'Âmbar',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Castanho-clara',
    value: 'Castanho-clara',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Castanho-escura',
    value: 'Castanho-escura',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
];
