export const hairColors = [
  {
    label: 'Selecione uma cor do cabelo',
    value: '',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Preto Profundo',
    value: 'Preto Profundo',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Preto Natural',
    value: 'Preto Natural',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Castanho Escuro',
    value: 'Castanho Escuro',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Castanho Médio',
    value: 'Castanho Médio',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Castanho Claro',
    value: 'Castanho Claro',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Loiro Escuro',
    value: 'Loiro Escuro',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Loiro Médio',
    value: 'Loiro Médio',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Loiro Claro',
    value: 'Loiro Claro',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Loiro Muito Claro',
    value: 'Loiro Muito Claro',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Loiro Clarissimo',
    value: 'Loiro Clarissimo',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Colorido',
    value: 'Colorido',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
];
