export const hairNuance = [
  {
    label: 'nuance de seu cabelo',
    value: '',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Sem reflexo / Natural',
    value: 'Sem reflexo / Natural',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Acinzentado',
    value: 'Acinzentado',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Violeta / Irisado',
    value: 'Violeta / Irisado',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Dourado',
    value: 'Dourado',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Acobreado',
    value: 'Acobreado',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Acaju',
    value: 'Acaju',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Vermelho',
    value: 'Vermelho',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
  {
    label: 'Marrom',
    value: 'Marrom',
    color: '',
    colorFont: '',
    backgroundColor: '',
  },
];
